### ISSUE TITLE
Hope you don't mind me asking.

### ISSUE THREAD

**Issue by CoderReece** [UAVXP/LeakNet-SDK#1]
But does anyone here have the "Processor Pack 5"
I used to have a copy but i lost it and half the downloads online are malware and adware.

**Comment by UAVXP** [comment]
@tryzombie501 https://yadi.sk/d/aIbDr3WIWgQpi

**Comment by CoderReece** [comment]
Brought this back to life because i didn't want to clutter the issues section with a new issue. But i believe github is breaking the dsw workspace file because when i open it nothing happens. 

Does this workspace look correct?

`Microsoft Developer Studio Workspace File, Format Version 6.00
# WARNING: DO NOT EDIT OR DELETE THIS WORKSPACE FILE!

###############################################################################

Project: "client"=.\cl_dll\client.dsp - Package Owner=<4>

Package=<5>
{{{
}}}

Package=<4>
{{{
}}}

###############################################################################

Project: "hl"=.\dlls\hl.dsp - Package Owner=<4>

Package=<5>
{{{
}}}

Package=<4>
{{{
}}}

###############################################################################

Global:

Package=<5>
{{{
}}}

Package=<3>
{{{
}}}

###############################################################################

`

**Comment by UAVXP** [comment]
@tryzombie501 All should be okay

**Comment by CoderReece** [comment]
figured it out github completely changes all files to unix instead of windows clr format and visual studio doesn't like that
