### ISSUE TITLE
LeakNet Crash after Loading a Map

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [UAVXP/LeakNet-SDK#2]
Well, i'm install the most recent version os LeakNet in my HL2 Beta folder, i have megapatch 3 according to instructions but when i'm load x map the game just crash

**Comment by UAVXP** [comment]
@xXxToxicBlueDustxXx That's not the place to report issues about LeakNet patch. It's the repository for developers. If you want to report issue about LeakNet patch - go to http://leaknet.tk/mantisbt/
